### ISSUE TITLE
iOS 启动报错 Null check operator used on a null value

### ISSUE THREAD

**Issue by mdddj** [anyinspect/anyinspect_app#2]
```dart
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:146:36)
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannelNetworkInfo.getWifiIP (package:network_info_plus_platform_interface/method_channel_network_info.dart:38:26)
#4      NetworkInfo.getWifiIP (package:network_info_plus/network_info_plus.dart:60:22)
#5      AnyInspect._getServerAddress (package:anyinspect/src/anyinspect.dart:69:38)
#6      AnyInspect.start (package:anyinspect/src/anyinspect.dart:92:34)
#7      main (package:fstore/main.dart:39:14)

```

版本
```dart
  anyinspect: ^0.1.1
  anyinspect_plugin_network: ^0.1.0
  anyinspect_plugin_shared_preferences: ^0.1.0
```

flutter doctor
```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] VS Code (version 1.62.3)
[✓] Proxy Configuration
[✓] Connected device (2 available)

• No issues found!

```

**Comment by lijy91** [comment]
需要在 main 开始处调用 `WidgetsFlutterBinding.ensureInitialized();`

```dart
import 'package:anyinspect/anyinspect.dart';
import 'package:anyinspect_plugin_network/anyinspect_plugin_network.dart';
import 'package:anyinspect_plugin_shared_preferences/anyinspect_plugin_shared_preferences.dart';

Future<void> main(List<String> args) async {
  // Must add this line.
  WidgetsFlutterBinding.ensureInitialized();

  AnyInspect anyInspect = AnyInspect.instance;
  anyInspect.addPlugin(AnyInspectPluginNetwork());
  anyInspect.addPlugin(AnyInspectPluginSharedPreferences());
  anyInspect.start();

  // ...
}
```
